# Generated by Django 3.2 on 2023-02-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipecomment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecomment',
            old_name='body',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='recipecomment',
            old_name='comment',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='comment',
        ),
    ]
